from fastapi import APIRouter, HTTPException, UploadFile, File, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from core.security import get_current_user
from core.config import settings
import pdfplumber
import io
import json
import re

router = APIRouter(prefix="/api/pdf-tools", tags=["pdf-tools"])

MODEL = "gemini-1.5-flash"


# ── Helpers ────────────────────────────────────────────────────────────────────

def _extract_pdf_text(file_bytes: bytes) -> str:
    text_pages = []
    with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text_pages.append(page_text.strip())
    return "\n\n".join(text_pages)


def _gemini():
    import google.generativeai as genai
    if not settings.gemini_api_key:
        raise HTTPException(status_code=503, detail="Gemini API key not configured.")
    genai.configure(api_key=settings.gemini_api_key)
    return genai.GenerativeModel(MODEL)


def _ask(prompt: str) -> str:
    model = _gemini()
    response = model.generate_content(prompt)
    raw = response.text.strip()
    raw = re.sub(r"^```[a-z]*\n?", "", raw)
    raw = re.sub(r"\n?```$", "", raw)
    return raw


def _ask_image(prompt: str, image_bytes: bytes, mime_type: str) -> str:
    import google.generativeai as genai
    from PIL import Image
    if not settings.gemini_api_key:
        raise HTTPException(status_code=503, detail="Gemini API key not configured.")
    genai.configure(api_key=settings.gemini_api_key)
    model = genai.GenerativeModel(MODEL)
    img = Image.open(io.BytesIO(image_bytes))
    response = model.generate_content([prompt, img])
    raw = response.text.strip()
    raw = re.sub(r"^```[a-z]*\n?", "", raw)
    raw = re.sub(r"\n?```$", "", raw)
    return raw


# ── PDF → PPT (Step 1: extract slides as JSON) ────────────────────────────────

@router.post("/pdf-to-ppt")
async def pdf_to_ppt(
    file: UploadFile = File(...),
    current_user: dict = Depends(get_current_user),
):
    """Extract slide content from a PDF as editable JSON."""
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are accepted")

    raw_text = _extract_pdf_text(await file.read())
    if not raw_text.strip():
        raise HTTPException(status_code=422, detail="Could not extract text from this PDF")

    prompt = (
        "Convert this question paper into presentation slides.\n"
        "Output a JSON object with:\n"
        '  "title": paper title or subject,\n'
        '  "subject": subject name,\n'
        '  "slides": array of {"title": string, "bullets": [string, ...]}\n'
        "One slide per question/section. Max 5 bullets per slide.\n"
        "Return ONLY valid JSON, no markdown fences.\n\n"
        f"TEXT:\n{raw_text[:8000]}"
    )
    raw = _ask(prompt)
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        raise HTTPException(status_code=500, detail="AI returned invalid slide data. Try again.")

    return {
        "title": data.get("title", file.filename.replace(".pdf", "")),
        "subject": data.get("subject", ""),
        "slides": data.get("slides", []),
    }


# ── Download PPTX (Step 2: build file from edited slides) ─────────────────────

class Slide(BaseModel):
    title: str
    bullets: list[str]

class DownloadPptxRequest(BaseModel):
    title: str
    subject: str
    slides: list[Slide]

@router.post("/download-pptx")
async def download_pptx(
    body: DownloadPptxRequest,
    current_user: dict = Depends(get_current_user),
):
    """Build and download a .pptx from edited slide JSON."""
    from pptx import Presentation
    from pptx.util import Inches

    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    cover = prs.slides.add_slide(prs.slide_layouts[0])
    cover.shapes.title.text = body.title or "Question Paper"
    cover.placeholders[1].text = body.subject or "Generated by DeskExam"

    for s in body.slides:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = s.title
        tf = slide.placeholders[1].text_frame
        tf.clear()
        for i, bullet in enumerate(s.bullets):
            if i == 0:
                tf.paragraphs[0].text = bullet
            else:
                p = tf.add_paragraph()
                p.text = bullet
                p.level = 1

    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)

    safe_title = re.sub(r"[^\w\s-]", "", body.title or "presentation")[:40].strip()
    return StreamingResponse(
        buf,
        media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        headers={"Content-Disposition": f'attachment; filename="{safe_title}.pptx"'},
    )


# ── PDF → LaTeX ────────────────────────────────────────────────────────────────

@router.post("/pdf-to-latex")
async def pdf_to_latex(
    file: UploadFile = File(...),
    current_user: dict = Depends(get_current_user),
):
    """Extract text from a PDF and convert to a complete LaTeX document."""
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are accepted")

    raw_text = _extract_pdf_text(await file.read())
    if not raw_text.strip():
        raise HTTPException(status_code=422, detail="Could not extract text from this PDF")

    prompt = (
        "Convert the following question paper text into a complete, compilable LaTeX document.\n"
        r"Use \documentclass{article}, section headers, enumerate for questions, "
        r"and $...$ or \[...\] for math." "\n"
        "Return ONLY the LaTeX source, no explanation.\n\n"
        f"TEXT:\n{raw_text[:10000]}"
    )
    latex = _ask(prompt)
    return {"latex": latex, "char_count": len(latex)}


# ── Photo → LaTeX ──────────────────────────────────────────────────────────────

@router.post("/photo-to-latex")
async def photo_to_latex(
    file: UploadFile = File(...),
    current_user: dict = Depends(get_current_user),
):
    """Upload a photo of a question paper and get back a LaTeX document."""
    allowed = {".jpg", ".jpeg", ".png", ".webp", ".gif"}
    ext = ("." + file.filename.rsplit(".", 1)[-1].lower()) if "." in file.filename else ""
    if ext not in allowed:
        raise HTTPException(status_code=400, detail="Accepted formats: JPG, PNG, WEBP, GIF")

    mime_map = {".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png",
                ".webp": "image/webp", ".gif": "image/gif"}

    prompt = (
        "This is a photo of a question paper. "
        "Convert every visible question, instruction, and mark scheme "
        "into a complete, compilable LaTeX document.\n"
        r"Use \documentclass{article}, enumerate for questions, $...$ for math." "\n"
        "Return ONLY the LaTeX source, no explanation."
    )
    latex = _ask_image(prompt, await file.read(), mime_map[ext])
    return {"latex": latex, "char_count": len(latex)}


# ── PDF → Editor ───────────────────────────────────────────────────────────────

@router.post("/pdf-to-editor")
async def pdf_to_editor(
    file: UploadFile = File(...),
    current_user: dict = Depends(get_current_user),
):
    """Extract questions from a PDF as structured JSON for the editor."""
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are accepted")

    raw_text = _extract_pdf_text(await file.read())
    if not raw_text.strip():
        raise HTTPException(status_code=422, detail="Could not extract text from this PDF")

    prompt = (
        "Extract all questions from this question paper.\n"
        "Return a JSON array of objects, each:\n"
        '  {"type": "MCQ"|"Short Answer"|"Long Answer"|"True/False",\n'
        '   "question": "string",\n'
        '   "options": ["A. ...", "B. ...", "C. ...", "D. ..."]  (MCQ only),\n'
        '   "marks": number}\n'
        "Return ONLY valid JSON, no markdown fences.\n\n"
        f"TEXT:\n{raw_text[:10000]}"
    )
    raw = _ask(prompt)
    try:
        questions = json.loads(raw)
    except json.JSONDecodeError:
        raise HTTPException(status_code=500, detail="AI returned invalid question data. Try again.")

    return {"questions": questions, "count": len(questions)}
